// This file was auto-generated by ML.NET Model Builder. 

using System;
using SinjulMSBHArchiveCodesML.Model;

namespace SinjulMSBHArchiveCodesML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Vendor_id = @"CMT",
                Passenger_count = 1F,
                Trip_time_in_secs = 1271F,
                Trip_distance = 3.8F,
                Payment_type = @"CRD",
                Fare_amount = 17.5F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Rate_code with predicted Rate_code from sample data...\n\n");
            Console.WriteLine($"Vendor_id: {sampleData.Vendor_id}");
            Console.WriteLine($"Passenger_count: {sampleData.Passenger_count}");
            Console.WriteLine($"Trip_time_in_secs: {sampleData.Trip_time_in_secs}");
            Console.WriteLine($"Trip_distance: {sampleData.Trip_distance}");
            Console.WriteLine($"Payment_type: {sampleData.Payment_type}");
            Console.WriteLine($"Fare_amount: {sampleData.Fare_amount}");
            Console.WriteLine($"\n\nPredicted Rate_code: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
